[package]
name = "fs-ledger"
version = "0.1.0"
authors = ["Ivan Tham <pickfire@riseup.net>"]
edition = "2021"

[dependencies]
lopdf = { version = "0.35.0", features = ["serde"] }
rayon = "1.10.0"
serde = "1"
serde_json = "1"
shellexpand = "3.1.0"
