[package]
name = "fs-ledger"
version = "0.1.0"
authors = ["Ivan Tham <pickfire@riseup.net>"]
edition = "2021"

[dependencies]
regex = { version = "1", default-features = false, features = ["std", "perf"] }
